-- Idea and code by Todd Maxey
-- github.com/toddmaxey
-- WireShark LUA script for decoding Citrix ADC (NetScaler) Reset Codes
-- Based on https://support.citrix.com/article/CTX200852/citrix-adc-netscaler-reset-codes-reference

-- Reset code to description table
local resetDescriptions = {
[9912] = "HTTP link incomplete due to no available memory.",
[9911] = "HTTP incomplete due to no available memory",
[9906] = "Local GSLB sites have been removed, send RST",
[9905] = "Database not responding",
[9904] = "Reset on AAA error",
[9903] = "GSLB feature is disabled. Donot accept any connections and close any existing ones",
[9902] = "HTML injection connection abort",
[9901] = "Cache buffer large data error",
[9900] = "PI reset",
[9831] = "Use it if no application data exist, but required",
[9890] = "Rewrite feature disabled when blocked on response side",
[9460] = "SQL link failed",
[9459] = "SQL bad server",
[9458] = "SQL no memory",
[9457] = "SQL server login failed",
[9456] = "SQL Login response before request",
[9886] = "Reset on VPN ng binding miss",
[9885] = "Diameter reset on bad ACK",
[9884] = "Reset to Server PCB",
[9883] = "Link PCB fail reset to client on CEA",
[9882] = "Reset to Client if no pending requests",
[9881] = "Reset on Diameter message without CE",
[9880] = "Memory alloc failure",
[9879] = "Parsing failed",
[9878] = "CEA untrackable, send RST to Client",
[9877] = "Reset for CEA on client PCB",
[9876] = "One to many link failed.",
[9875] = "Client connection is closed, send RST to server",
[9874] = "NSB hold limit reached",
[9873] = "Agsvc MCMX failure",
[9872] = "Websocket upgrade request dropped due to websocket disabled in http profile",
[9871] = "MSSQL memory allocation failure",
[9870] = "SQL login parse error",
[9868] = "MSSQL login errors",
[9866] = "URL policy transform error",
[9865] = "CVPN MCMX error",
[9864] = "CVPN HINFO restore failed",
[9863] = "Reset to old connection when new connection is established and old one is still not freed",
[9862] = "Reset to Client as it resulted in duplicate server connection",
[9861] = "Connection on a push vserver, when push disabled on client vserver",
[9860] = "The pcb->link of this connection was cleaned for some reason, so resetting this pcb",
[9859] = "A new client connection request was made deferrable by server on the label",
[9858] = "Reset on Rechunk abort",
[9857] = "Reset on Flushing HTTP waiting PCB",
[9856] = "Reset on Appfw ASYNC failure",
[9855] = "For HTTP/SSL vservers, SO threshold has reached",
[9854] = "Indirect GSLB sites tried to establish connection",
[9853] = "MSSQL Auth response error",
[9852] = "RTSP (ALG) session handling error",
[9851] = "DNS TCP failure ( invalid payload len etc)",
[9850] = "DNS TCP connection untrackable due to failure of compact NSB etc",
[9849] = "Reset on GSLB conflict due to mis configuration",
[9848] = "Reset on connection accepted during configuration change(SSL)",
[9847] = "Delta compression aborted or failed",
[9846] = "Delta compression aborted or failed",
[9845] = "Reset on Appsec policy",
[9844] = "SSL reneg max NSB limit reached or alloc failure",
[9843] = "Monitor wide IP probe",
[9842] = "SSL NSB allocation failure",
[9841] = "SSL/DTLS split packet failure",
[9839] = "SSL MAX NSB hold limit reached",
[9838] = "NSBE_DBG_RST_SSL_BAD_RECORD: This code refers to error looking up SSL record when handling a request or a response.",
[9837] = "SSLV2 record too large",
[9836] = "DTLS record zero length",
[9835] = "DTLS record too large",
[9834] = "Reset while flushing all SPCB, during fips or hsm init",
[9833] = "Fatal SSL error",
[9401] = "When you reach maximum system capacity flushing existing connections based time order to accommodate new connections. Or when we remove an configured entity which as associated connections those connection will be reset.",
[9400] = "Reset server connection which are in reusepool and are not reusable because of TCP or Session level properties. Usually this is done when we need to open new connections but there is limit on connection we can open to the server and there are some already built up connections which are not reusable.",
[9830] = "Reset on sessions matching ACL DENY rule",
[9829] = "Reset on GSLB other site down or out of reach",
[9827] = "Reset on SSL config change",
[9826] = "Not enough memory for NET buffers",
[9825] = "DBG_WRONG_GSLBRECDLEN: This code is an MEP error reset code, typically between mixed versions.",
[9824] = "Reset on AAA orphan connections.",
[9823] = "Reset when the NSC_AAAC cookie is malformed in a request or /vpn/apilogin.html request does not have a query part, memory allocation failures in certificate processing.",
[9822] = "SSL cipher changed, flush the connection created for old cipher.",
[9821] = "SSL feature disabled, reset the connection.",
[9820] = "SSL card operation failed.",
[9819] = "Reset on failing to allocate memory for SPCB.",
[9818] = "Bad SSL header value.",
[9817] = "SSL connection received at the time of bound certificate changing (configuration change).",
[9816] = "Bad SSL record.",
[9814] = "NSDBG_RST_PETRIGGER: This reset code is used when a request or response matches a Policy Engine policy, whose action is RESET.",
[9813] = "Closing the SSF connection.",
[9812] = "Connection flushing because existing IP address is removed from the configuration.",
[9811] = "NSDBG_RST_ERRHANDLER: This reset code is used with SSL. After sending a Fatal Alert, the NetScaler sends a RST packet with this error code. If the client does not display any supported ciphers to the NetScaler appliance, the appliance sends a Fatal Alert and then this RST packet.",
[9810] = "When responses match the configured NAI status code.",
[9800] = "NSDBG_RST_PROBE: This connections used for monitoring the service are reset due to timeout.",
[9889] = "Reset on missing dynamic processing context (LUA)",
[9451] = "SQL response failed.",
[10032] = "SIPALG: Header parsing failed",
[9311] = "DHT retry failed.",
[9310] = "TCP KA probing failed.",
[9309] = "Small window protection feature resetting the connection.",
[9308] = "Small window protection feature resetting the connection.",
[9307] = "Small window protection feature resetting the connection.",
[9306] = "TCP buffering is undone due to duplicate TCPB enablement.",
[9305] = "Server sent back ACK to our SYN (ACK number did not match).",
[9304] = "NSDBG_RST_LINK_GIVEUPS: This reset code might be part of a backend-persistence mechanism, which is used to free resources on the NetScaler. By default, the NetScaler uses a zero window probe 7 times before giving up and resetting the connection. By disabling this mechanism, the appliance holds the sessions without this limit. The following is the command to disable the persistence probe limit: root@ns# nsapimgr -ys limited_persistprobe=0 The default value is 1, which limits to 7 probes, which is around 2 minutes. Setting the value to zero disables it and keeps the session open as long as the server sends an ACK signal in response to the probes.",
[9303] = "NSDBG_RST_ZSSSR: This code refers to an idle timeout or a zombie timeout. This code is set by the zombie connection cleanup routine, a connection has timed out. When the status of a service is down, existing TCP connections to that service are reset with this code (TCP window size 9300/9301, zombie timer). If the NetScaler appliance receives a segment from one of these connections, which is already reset, send another reset (TCP window size 8201, stray packet).",
[9302] = "NSDBG_RST_ZSSSR: This code refers to an idle timeout or a zombie timeout. This code is set by the zombie connection cleanup routine, a connection has timed out. When the status of a service is down, existing TCP connections to that service are reset with this code (TCP window size 9300/9301, zombie timer). If the NetScaler appliance receives a segment from one of these connections, which is already reset, send another reset (TCP window size 8201, stray packet).",
[9301] = "NSDBG_RST_ZSSSR: This code refers to an idle timeout or a zombie timeout. This code is set by the zombie connection cleanup routine, a connection has timed out. When the status of a service is down, existing TCP connections to that service are reset with this code (TCP window size 9300/9301, zombie timer). If the NetScaler appliance receives a segment from one of these connections, which is already reset, send another reset (TCP window size 8201, stray packet).",
[9300] = "NSDBG_RST_ZSSSR: This code refers to an idle timeout or a zombie timeout. This code is set by the zombie connection cleanup routine, a connection has timed out. When the status of a service is down, existing TCP connections to that service are reset with this code (TCP window size 9300/9301, zombie timer). If the NetScaler appliance receives a segment from one of these connections, which is already reset, send another reset (TCP window size 8201, stray packet).",
[9454] = "SQL NSB hold failed",
[9704] = "Reset when NSB dropped due to hold limit or error in transaction etc.",
[9702] = "The data received after FIN is received.",
[9701] = "NSDBG_RST_NEST / NSDBG_RST_ACK_PASS: The NetScaler software release 9.1 and the later versions, this code indicates #define NSBE_DBG_RST_ACK_PASS. It indicates that a RST code was forwarded as in the preceding RST code 9700, and the ACK flag was also set.",
[9700] = "NSDBG_RST_PASS: This code indicates that the NetScaler appliance receives a TCP RST code from either the client or the server, and is transferring it. For example, the back end server sends a RST code, and the NetScaler appliance forwards it to the client with this code.",
[9888] = "Reset to AAA client if Cluster sync in progress",
[10033] = "SIPALG: Body parsing failed",
[9455] = "SQL Server First Packet",
[9222] = "This is sent when the response is RFC non-compliant. The issue is caused by both Content-Length and Transfer-Encoding in response being invalid, which may lead to a variety of attacks and leads to the reset.",
[9221] = "vurl comes with a domain shard that’s no longer valid.",
[9220] = "Cannot allocate new NSB and so many other reasons.",
[9219] = "NSB allocation failure.",
[9218] = "Terminated due to extra orphan data.",
[9217] = "HTTP state machine error because of more than content length body.",
[9216] = "Cache async no memory.",
[9214] = "Cache res store failed.",
[9212] = "HTTP Invalid request.",
[9210] = "Corrupt packets.",
[9209] = "Chunk tracking failed.",
[9208] = "Incomplete response processing error, see incompHdrDelay setting httpprofiles.",
[9207] = "Invalid header reassembly parsing.",
[9206] = "HTTP tracking failed due to invalid HTTP request/response header.",
[9205] = "NSDBG_RST_CHUNK_FAIL: This code indicates that the NetScaler appliance experienced issues with the chunked encoding in the HTTP response from the server.",
[9204] = "HTTP connection multiplexing error. Server sent response packets belonging to previous transaction.",
[9203] = "NSDBG_RST_CLT_CHK_MIX: This code refers to the server sending a FIN for a previous client over a reused connection.",
[9202] = "NSDBG_RST_LERRCDM:  CDM refers to Check Data Mixing. This reset code is set when there is a TCP sequence mismatch in the first data packet, arriving from a recently reused server connection.",
[9201] = "HTTP connection multiplexing error. Server sent response packets belonging to previous transaction.",
[10038] = "SIPALG: BA insertion failed",
[10042] = "SIPALG: Pre translation ops failed",
[10040] = "SIPALG: Post translation ops failed",
[10039] = "SIPALG: DHT failure",
[9453] = "SQL UNK not linked.",
[10037] = "SIPALG: Length replacement failure",
[10036] = "SIPALG: Remaining IP replacement failure",
[10035] = "SIPALG: SDP header failure",
[10034] = "SIPALG: SIP header failure",
[9602] = "When SSL VPN CS probe limit exceeded",
[9601] = "Reset when Number of data packets with Sequence ACK mismatch > nscfg_max_orphan_pkts",
[9600] = "Reset when Number of packets with Sequence ACK mismatch > nscfg_max_orphan_pkts",
[10030] = "Connection breached maximum packet credits configured",
[10029] = "SSL: Hit the ratelimit",
[10028] = "SSL: HSM error client",
[10027] = "SSL: HSM operation failed",
[10026] = "SMPP: MSG without bind or not request message after bind",
[10024] = "SMPP: link failed",
[10023] = "SMPP: Parsing failed",
[10022] = "SMPP: Bind response on client",
[10020] = "SMPP: NSB hold limit reached",
[10019] = "SMPP: Bind to client failed",
[10018] = "SMPP unknown error",
[10017] = "SMPP reset if no pending requests",
[10016] = "SMPP no memory available",
[9887] = "Reset on failed to send a request to broker (VPN)",
[9450] = "SQL HS failed.",
[10006] = "Kill an RDP connection",
[10005] = "MPTCP SYN retries reached MAXretries.",
[10004] = "Kill an ICA connection",
[10003] = "ICA link no available memory",
[10002] = "ICA no available memory",
[10001] = "ICA link parse error",
[10000] = "ICA parse error",
[9832] = "Application error",
[9452] = "SQL request list failed.",
[9983] = "MPTCP invalid payload size",
[9982] = "invalid syn/ack/seq is received for NS's SYN+TFOC+DATA",
[9981] = "Closing auditlog connection",
[9980] = "Reset on MPTCP close",
[9979] = "MPTCP subflow FIN received or any other signals received on pre est SF",
[9978] = "MPTCP SYN retries reached MAXretries.",
[9977] = "MPTCP token collision is found",
[9976] = "MPTCP MAX retries on KA probes has reached.",
[9975] = "PCB waitQ insertion failed",
[9974] = "RST terminated at TCP layer",
[9973] = "Reset on rest of SF after fallback to infinite map as only one SF should be present",
[9972] = "MPTCP reset if multiple SFs are present",
[9971] = "MPTCP invalid/bad MAP",
[9970] = "BW Connection Close",
[9969] = "MPTCP, if NS in fallback mode, DSS should only for infinite map.",
[9968] = "MPTCP fast close received",
[9967] = "MPTCP plain ACK fallback failure",
[9966] = "MPTCP RSSF filter failure",
[9965] = "MPTCP, established SF replaced",
[9964] = "Invalid Client or NS key",
[9963] = "MPTCP checksum failure",
[9100] = "NSDBG_RST_ORP: This code refers to an orphan HTTP connection. Probably, a connection where data is initially seen either from the server or client, but stopped because of some reason, without closing the TCP session. It indicates that the client request was not properly terminated. Therefore, the NetScaler appliance waits for the request to be completed. After a timeout, the NetScaler appliance resets the connection with the code 9100.",
[9961] = "MP join SYN reset",
[9960] = "MPTCP options error",
[9959] = "Not used",
[9958] = "Not used+C187:C199",
[9957] = "AppQoS Persistent sercvice is down",
[9956] = "QOS incomplete POST handling error",
[9953] = "Reset on triggering of timeout action",
[9952] = "Reset on SSL FATAL ALERT RCVD",
[9951] = "SSL incomplete record",
[8214] = "MSS sent in SYN exceeded the MSS corresponding to NIC MTU and/or VLAN MTU.",
[8213] = "Sure Connect feature, bad client sending post on connection which is closing.",
[8212] = "Stray packet (no listening service or listening service is present but SYN cookie does not match or there is no corresponding connection information). 8212 is specifically for SYN stray packets.",
[8211] = "Cleanup of idle connections.",
[8210] = "HTTP DoS protection feature error, bad client request.",
[8209] = "Could not allocate memory for the packet, system out of memory.",
[8208] = "Resets the connection when you receive more than the configured value of duplicate retransmissions.",
[8207] = "Received SYN on established connection which is within the window. Protects from spoofing attacks.",
[8206] = "Received a bad packet in TCPS_SYN_SENT state (non RST packet). Usually happens if the 4 tuples are reused and you receive packet from the old connection.",
[8205] = "ACK number in the final ACK from peer during connection establishment is wrong.",
[8204] = "Client retransmitted SYN with the wrong sequence number.",
[8202] = "NSDBG_RST_CSTRAY: This code is triggered when the NetScaler appliance receives data through a connection, which does not have a PCB, and its SYN cookie has expired.",
[8201] = "NSDBG_RST_SSTRAY, 8201 – NSDBG_RST_SSTRAY",
[9962] = "MP join FINAL ACK reset",
[8196] = "SSL bad record.",
[9915] = "Speedy split packet at header failed",
[9914] = "Cache Response error/AAA",
[9913] = "Send RST for SPDY errors"
}

-- Function to display reset code information
function displayResetInfo(resetCode)
    local description = resetDescriptions[resetCode]
    if description then
        return string.format("Reset Code: %d\nDescription: %s", resetCode, description)
    else
        return string.format("Reset Code: %d\nDescription: Unknown", resetCode)
    end
end

-- Wireshark display filter
local filter = "tcp.flags.reset == 1 and tcp.window_size_value >= 8146 and tcp.window_size_value <= 10042"

-- Apply filter
local tap = Listener.new(nil, filter)

-- Callback function to process packets
function tap.packet(pinfo, tvb, tapdata)
    local resetCodeField = Field.new("tcp.window_size_value")
    local resetCode = resetCodeField().value

    if resetDescriptions[resetCode] then
        local resetInfo = displayResetInfo(resetCode)
        pinfo.cols.info:set(string.format("Citrix Reset: %s", resetInfo))
    end
end

